### ISSUE TITLE
calculateSimMatrix orgdb error

### ISSUE THREAD

**Issue by gaelanm** [ssayols/rrvgo#2]
Hello,

I am trying to analyze a list of human GO terms and receive the following error:

In calculateSimMatrix(x, orgdb = "org.Hs.eg.db", ont = "BP", method = "Rel") :
  No terms were found in orgdb for BP

I was curious if there any considerations for the structure of the input that could be contributing to this error? It is a .txt of newline-separated terms. the data can load in easily enough, however, I am not too sure why rrvgo is not recognizing the ontology terms.

Any help would be appreciated.

**Comment by ssayols** [comment]
Hi @gaelanm ,
`calculateSimMatrix` expects a character vector of GO IDs (eg. `x <- c("GO:0140014", "GO:0000280", "GO:0048285", "GO:0000070", "GO:0051301", "GO:0007059")`). Note that these GO IDs should match the right sub-ontology they belong to (BP == Biological Process; MF == Molecular Function; CC == Cellular Compartment).

Take a look at the help page of the `calculateSimMatrix` for a common example of a data.frame containing the result of a GO enrichment analysis, and the column that should be passed to the function in order to get the similarity matrix among terms:

```R
R> library(rrvgo)
R> go_analysis <- read.delim(system.file("extdata/example.txt", package="rrvgo"))
R> head(go_analysis)
                   ID                          Description GeneRatio   BgRatio       pvalue     p.adjust       qvalue
GO:0140014 GO:0140014             mitotic nuclear division    29/189 201/11248 2.813076e-19 8.475799e-16 7.684140e-16
GO:0000280 GO:0000280                     nuclear division    31/189 274/11248 1.996472e-17 3.007685e-14 2.726761e-14
GO:0048285 GO:0048285                    organelle fission    32/189 303/11248 4.437103e-17 4.456330e-14 4.040099e-14
GO:0000070 GO:0000070 mitotic sister chromatid segregation    21/189 109/11248 7.446719e-17 5.609241e-14 5.085325e-14
GO:0051301 GO:0051301                        cell division    37/189 442/11248 2.627553e-16 1.583363e-13 1.435474e-13
GO:0007059 GO:0007059               chromosome segregation    26/189 200/11248 3.181389e-16 1.597588e-13 1.448369e-13

R> simMatrix <- calculateSimMatrix(go_analysis$ID, orgdb="org.Hs.eg.db", ont="BP", method="Rel")
```

cheers

**Comment by gaelanm** [comment]
Ah this makes a lot more sense! Thank you very much.
