### ISSUE TITLE
option "scores = NULL" is not working in reduceSimMatrix 

### ISSUE THREAD

**Issue by parkjooyoung99** [ssayols/rrvgo#26]
I am trying to use the function reduceSimMatrix without giving a score like below code: 

```
go_analysis <- read.delim(system.file("extdata/example.txt", package="rrvgo"))
simMatrix <- calculateSimMatrix(go_analysis$ID, orgdb="org.Hs.eg.db", ont="BP", method="Rel")
# scores <- setNames(-log10(go_analysis$qvalue), go_analysis$ID)
reducedTerms <- reduceSimMatrix(simMatrix, scores = NULL, threshold=0.7, orgdb="org.Hs.eg.db")
```
however it is giving an error of 
```
Error in reduceSimMatrix(simMatrix, scores = NULL, threshold = 0.7, orgdb = "org.Hs.eg.db") : 
  Scores vector does not contain all terms in the similarity matrix
```

I bet it is from the starting point (# check function arguments) after reviewing the [source code ](https://rdrr.io/bioc/rrvgo/src/R/rrvgo.R). Can you go over and see what is happening? 

Thank you!

**Comment by ssayols** [comment]
Please note that the source code you link is from a third-party website which I'm not affiliated nor I have control to what they publish. The code is actually from an old version (1.2.0) which doesn't correspond with the version you're running. No idea why you go there, instead of looking at the **only source of truth** [here in Github](https://github.com/ssayols/rrvgo/blob/27dcbbb11064c2987d17105bad64210ee8680a6e/R/rrvgo.R#L65).

In the current version, the parameter `scores=` in `reduceSimMatrix()` can take 3 different values, as described in the function's documentation (`?reduceSimMatrix`):

```
  scores: one of c("uniqueness", "size"), or a *named* vector with
          scores provided for each term, where higher values favor
          choosing the term as the cluster representative. The default
          "uniqueness" uses a score reflecting how unique the term is.
          Note: if you like to use p-values as scores, consider
          -1*log-transforming them (`-log(p)`)
```

So **no**, `scores=NULL` is not valid (although I may somewhat agree that the error message is not 100% helpful).
