### ISSUE TITLE
Bug in treemapPlot() function

### ISSUE THREAD

**Issue by aa20g217** [ssayols/rrvgo#8]
Hey,

when I am trying to plot a treemap plot with a title, I am getting the following error:
`treemapPlot(reducedTerms,size="score",title="Plot title")`
`Error in treemap::treemap(reducedTerms, index = c("parentTerm", "term"),  : 
  formal argument "title" matched by multiple actual arguments`

As far as I understood this error is caused by line number 77- 80 in https://github.com/ssayols/rrvgo/blob/master/R/plotlib.R file.

I will highly appreciate any help or suggestions.

Thank you.

**Comment by ssayols** [comment]
For whatever reason we were forcing the treemap to have no title.
I just patched the code to allow setting a title (still, defaults to no title).
Until it's rolled out to Bioconductor, you can install the patched version using devtools:

```R
devtools::install_github("ssayols/rrvgo")
```
Please reopen the ticket if you have any feedback.
cheers,
Sergi

**Comment by aa20g217** [comment]
Could you please also provide the flexibility to change the color pallets as well?

**Comment by ssayols** [comment]
that's a bit more complicated. The color palettes are hardcoded because we want to keep consistency between multiple plots in terms of which colors get assigned to each category.

We could of course think of allowing the user to change the color palette in all plotting functions. But that's something that requires a bit more study from our side.

In the meantime, let me suggest to use the `treemap::treemap()` function instead, with whatever further parameters you'd like to use (title, palette, ...). These 4 are the important parameters in the call that you need to manually do the same plot as `rrvgo` does:
```R
treemap::treemap(reducedTerms,
                 index = c("parentTerm", "term"),
                 vSize = "score",
                 type = "index")
```
You can see the full call with:
```R
rrvgo::treemapPlot
```
